import {
  LayoutDashboard,
  Building2,
  Briefcase,
  Compass,
  FileUser,
  Users,
  Kanban,
  MessageSquare,
  ClipboardCheck,
  Trophy,
  GraduationCap,
  BookOpen,
  Contact,
  Calendar,
  CheckSquare,
  FolderOpen,
  BarChart3,
  Settings,
} from 'lucide-react';

export const NAV_ITEMS = [
  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { href: '/empresas', label: 'Empresas', icon: Building2 },
  { href: '/vacantes', label: 'Vacantes', icon: Briefcase },
  { href: '/discovery', label: 'Discovery Comercial', icon: Compass },
  { href: '/perfil-cargo', label: 'Perfil del Cargo', icon: FileUser },
  { href: '/candidatos', label: 'Candidatos', icon: Users },
  { href: '/ats', label: 'ATS', icon: Kanban },
  { href: '/entrevistas', label: 'Entrevistas', icon: MessageSquare },
  { href: '/evaluaciones', label: 'Evaluaciones', icon: ClipboardCheck },
  { href: '/finalistas', label: 'Finalistas', icon: Trophy },
  { href: '/onboarding', label: 'Onboarding', icon: GraduationCap },
  { href: '/academia', label: 'Academia Comercial', icon: BookOpen },
  { href: '/crm', label: 'CRM', icon: Contact },
  { href: '/calendario', label: 'Calendario', icon: Calendar },
  { href: '/tareas', label: 'Tareas', icon: CheckSquare },
  { href: '/documentos', label: 'Documentos', icon: FolderOpen },
  { href: '/reportes', label: 'Reportes', icon: BarChart3 },
  { href: '/configuracion', label: 'Configuración', icon: Settings },
];
